jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      # --- PASSO 1: Criar a pasta se não existir ---
      - name: Preparar Servidor (Pasta do Lab)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            sudo mkdir -p /var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}
            sudo chown -R ${{ vars.SSH_USER }}:${{ vars.SSH_USER }} /var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}

      # --- PASSO 2: Enviar os arquivos ---
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          source: "."
          target: "/var/inetpub/wwwroot/lab${{ vars.ALUNO_NUM }}"

      # --- PASSO 3: Reiniciar o Serviço ---
      - name: Atualizar Docker Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            docker service update --force labs_lab${{ vars.ALUNO_NUM }}