name: Deploy Inetz Lab
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Silencia os avisos de Node.js 20 para o futuro (Junho/2026)
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: 📂 Sincronizar Arquivos (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          source: "."
          target: "/var/inetpub/wwwroot/projetos/lab${{ vars.ALUNO_NUM }}"

      - name: 🚀 Refresh no Docker Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            # Força o Swarm a reiniciar o serviço com os novos arquivos mapeados
            # O nome do serviço segue o padrão: NomeDaStack_NomeDoServico
            docker service update --force inetz-labs_lab${{ vars.ALUNO_NUM }}